package dungeons_and_dragons.entity;
// Generated Jan 31, 2017 10:00:34 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 * Characters generated by hbm2java
 */
@Entity
public class Characters implements java.io.Serializable {

    @Id
    private int id;
    private int userId;
    private String level;
    private String inspiration;
    private String armorClass;
    private String initiative;
    private String speed;
    private String proficiencyBonus;
    private String maxHp;
    private String curHp;
    private String tempHp;
    private String xp;
    private Integer deathSaveSuccess;
    private Integer deathSaveFail;
    private String strength;
    private String dexterity;
    private String constitution;
    private String intelligence;
    private String wisdom;
    private String charisma;
    private String strMod;
    private String dexMod;
    private String conMod;
    private String intMod;
    private String wisMod;
    private String chaMod;
    private String strSave;
    private String dexSave;
    private String conSave;
    private String intSave;
    private String wisSave;
    private String chaSave;
    private String class_;
    private String background;
    private String playerName;
    private String charName;
    private String race;
    private String alignment;
    private String personalityTraits;
    private String ideals;
    private String bonds;
    private String flaws;
    private String hitDice;
    private String features;
    private String weapon1;
    private String weapon2;
    private String weapon3;
    private String attackBonus1;
    private String attackBonus2;
    private String attackBonus3;
    private String dmgType1;
    private String dmgType2;
    private String dmgType3;
    private String attacks;
    private String equipment;
    private String copper;
    private String silver;
    private String electrum;
    private String gold;
    private String platinum;
    private String passiveWisdom;
    private String language;
    private String proficiencies;

    public Characters() {
        this.id = -10;
        this.level = "";
        this.inspiration = "";
        this.armorClass = "";
        this.initiative = "";
        this.speed = "";
        this.proficiencyBonus = "";
        this.maxHp = "";
        this.curHp = "";
        this.tempHp = "";
        this.xp = "";
        this.deathSaveSuccess = -10;
        this.deathSaveFail = -10;
        this.strength = "";
        this.dexterity = "";
        this.constitution = "";
        this.intelligence = "";
        this.wisdom = "";
        this.charisma = "";
        this.strMod = "";
        this.dexMod = "";
        this.conMod = "";
        this.intMod = "";
        this.wisMod = "";
        this.chaMod = "";
        this.strSave = "";
        this.dexSave = "";
        this.conSave = "";
        this.intSave = "";
        this.wisSave = "";
        this.chaSave = "";
        this.class_ = "";
        this.background = "";
        this.charName = "";
        this.playerName = "";
        this.race = "";
        this.alignment = "";
        this.personalityTraits = "";
        this.ideals = "";
        this.bonds = "";
        this.flaws = "";
        this.hitDice = "";
        this.features = "";
        this.weapon1 = "";
        this.weapon2 = "";
        this.weapon3 = "";
        this.attackBonus1 = "";
        this.attackBonus2 = "";
        this.attackBonus3 = "";
        this.dmgType1 = "";
        this.dmgType2 = "";
        this.dmgType3 = "";
        this.attacks = "";
        this.equipment = "";
        this.copper = "";
        this.silver = "";
        this.electrum = "";
        this.gold = "";
        this.platinum = "";
        this.passiveWisdom = "";
        this.language = "";
        this.proficiencies = "";
    }

    public Characters(int id) {
        this.id = id;
    }

    public Characters(int id, String level, String inspiration, String armorClass, String initiative, String speed,
            String proficiencyBonus, String maxHp, String curHp, String tempHp, String xp, Integer deathSaveSuccess, 
            Integer deathSaveFail, String strength, String dexterity, String constitution, 
            String intelligence, String wisdom, String charisma, String strMod, 
            String dexMod, String conMod, String intMod, String wisMod, String chaMod,
            String strSave, String dexSave, String conSave, String intSave, String wisSave, 
            String chaSave, String class_, String background, String playerName, String charName, String race, String alignment, String personalityTraits, String ideals, String bonds, String flaws, String hitDice, String features, String weapon1, String weapon2, String weapon3, String attackBonus1, String attackBonus2, String attackBonus3, String dmgType1, String dmgType2, String dmgType3, String attacks, String equipment, String copper, String silver, String electrum, String gold, String platinum, String passiveWisdom, String language, String proficiencies) {
        this.id = id;
        this.level = level;
        this.inspiration = inspiration;
        this.armorClass = armorClass;
        this.initiative = initiative;
        this.speed = speed;
        this.proficiencyBonus = proficiencyBonus;
        this.maxHp = maxHp;
        this.curHp = curHp;
        this.tempHp = tempHp;
        this.xp = xp;
        this.deathSaveSuccess = deathSaveSuccess;
        this.deathSaveFail = deathSaveFail;
        this.strength = strength;
        this.dexterity = dexterity;
        this.constitution = constitution;
        this.intelligence = intelligence;
        this.wisdom = wisdom;
        this.charisma = charisma;
        this.strMod = strMod;
        this.dexMod = dexMod;
        this.conMod = conMod;
        this.intMod = intMod;
        this.wisMod = wisMod;
        this.chaMod = chaMod;
        this.strSave = strSave;
        this.dexSave = dexSave;
        this.conSave = conSave;
        this.intSave = intSave;
        this.wisSave = wisSave;
        this.chaSave = chaSave;
        this.class_ = class_;
        this.background = background;
        this.charName = charName;
        this.playerName = playerName;
        this.race = race;
        this.alignment = alignment;
        this.personalityTraits = personalityTraits;
        this.ideals = ideals;
        this.bonds = bonds;
        this.flaws = flaws;
        this.hitDice = hitDice;
        this.features = features;
        this.weapon1 = weapon1;
        this.weapon2 = weapon2;
        this.weapon3 = weapon3;
        this.attackBonus1 = attackBonus1;
        this.attackBonus2 = attackBonus2;
        this.attackBonus3 = attackBonus3;
        this.dmgType1 = dmgType1;
        this.dmgType2 = dmgType2;
        this.dmgType3 = dmgType3;
        this.attacks = attacks;
        this.equipment = equipment;
        this.copper = copper;
        this.silver = silver;
        this.electrum = electrum;
        this.gold = gold;
        this.platinum = platinum;
        this.passiveWisdom = passiveWisdom;
        this.language = language;
        this.proficiencies = proficiencies;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getInspiration() {
        return this.inspiration;
    }

    public void setInspiration(String inspiration) {
        this.inspiration = inspiration;
    }

    public String getArmorClass() {
        return this.armorClass;
    }

    public void setArmorClass(String armorClass) {
        this.armorClass = armorClass;
    }

    public String getInitiative() {
        return this.initiative;
    }

    public void setInitiative(String initiative) {
        this.initiative = initiative;
    }

    public String getSpeed() {
        return this.speed;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public String getProficiencyBonus() {
        return this.proficiencyBonus;
    }

    public void setProficiencyBonus(String proficiencyBonus) {
        this.proficiencyBonus = proficiencyBonus;
    }

    public String getMaxHp() {
        return this.maxHp;
    }

    public void setMaxHp(String maxHp) {
        this.maxHp = maxHp;
    }

    public String getCurHp() {
        return this.curHp;
    }

    public void setCurHp(String curHp) {
        this.curHp = curHp;
    }

    public String getTempHp() {
        return this.tempHp;
    }

    public void setTempHp(String tempHp) {
        this.tempHp = tempHp;
    }

    public String getXp() {
        return this.xp;
    }

    public void setXp(String xp) {
        this.xp = xp;
    }

    public Integer getDeathSaveSuccess() {
        return this.deathSaveSuccess;
    }

    public void setDeathSaveSuccess(Integer deathSaveSuccess) {
        this.deathSaveSuccess = deathSaveSuccess;
    }

    public Integer getDeathSaveFail() {
        return this.deathSaveFail;
    }

    public void setDeathSaveFail(Integer deathSaveFail) {
        this.deathSaveFail = deathSaveFail;
    }

    public String getStrength() {
        return this.strength;
    }

    public void setStrength(String strength) {
        this.strength = strength;
    }

    public String getDexterity() {
        return this.dexterity;
    }

    public void setDexterity(String dexterity) {
        this.dexterity = dexterity;
    }

    public String getConstitution() {
        return this.constitution;
    }

    public void setConstitution(String constitution) {
        this.constitution = constitution;
    }

    public String getIntelligence() {
        return this.intelligence;
    }

    public void setIntelligence(String intelligence) {
        this.intelligence = intelligence;
    }

    public String getWisdom() {
        return this.wisdom;
    }

    public void setWisdom(String wisdom) {
        this.wisdom = wisdom;
    }

    public String getCharisma() {
        return this.charisma;
    }

    public void setCharisma(String charisma) {
        this.charisma = charisma;
    }

    public String getStrMod() {
        return this.strMod;
    }

    public void setStrMod(String strMod) {
        this.strMod = strMod;
    }

    public String getDexMod() {
        return this.dexMod;
    }

    public void setDexMod(String dexMod) {
        this.dexMod = dexMod;
    }

    public String getConMod() {
        return this.conMod;
    }

    public void setConMod(String conMod) {
        this.conMod = conMod;
    }

    public String getIntMod() {
        return this.intMod;
    }

    public void setIntMod(String intMod) {
        this.intMod = intMod;
    }

    public String getWisMod() {
        return this.wisMod;
    }

    public void setWisMod(String wisMod) {
        this.wisMod = wisMod;
    }

    public String getChaMod() {
        return this.chaMod;
    }

    public void setChaMod(String chaMod) {
        this.chaMod = chaMod;
    }

    public String getStrSave() {
        return this.strSave;
    }

    public void setStrSave(String strSave) {
        this.strSave = strSave;
    }

    public String getDexSave() {
        return this.dexSave;
    }

    public void setDexSave(String dexSave) {
        this.dexSave = dexSave;
    }

    public String getConSave() {
        return this.conSave;
    }

    public void setConSave(String conSave) {
        this.conSave = conSave;
    }

    public String getIntSave() {
        return this.intSave;
    }

    public void setIntSave(String intSave) {
        this.intSave = intSave;
    }

    public String getWisSave() {
        return this.wisSave;
    }

    public void setWisSave(String wisSave) {
        this.wisSave = wisSave;
    }

    public String getChaSave() {
        return this.chaSave;
    }

    public void setChaSave(String chaSave) {
        this.chaSave = chaSave;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    public String getBackground() {
        return this.background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getPlayerName() {
        return this.playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    public String getCharName() {
        return this.charName;
    }

    public void setCharName(String charName) {
        this.charName = charName;
    }

    public String getRace() {
        return this.race;
    }

    public void setRace(String race) {
        this.race = race;
    }

    public String getAlignment() {
        return this.alignment;
    }

    public void setAlignment(String alignment) {
        this.alignment = alignment;
    }

    public String getPersonalityTraits() {
        return this.personalityTraits;
    }

    public void setPersonalityTraits(String personalityTraits) {
        this.personalityTraits = personalityTraits;
    }

    public String getIdeals() {
        return this.ideals;
    }

    public void setIdeals(String ideals) {
        this.ideals = ideals;
    }

    public String getBonds() {
        return this.bonds;
    }

    public void setBonds(String bonds) {
        this.bonds = bonds;
    }

    public String getFlaws() {
        return this.flaws;
    }

    public void setFlaws(String flaws) {
        this.flaws = flaws;
    }

    public String getHitDice() {
        return this.hitDice;
    }

    public void setHitDice(String hitDice) {
        this.hitDice = hitDice;
    }

    public String getFeatures() {
        return this.features;
    }

    public void setFeatures(String features) {
        this.features = features;
    }

    public String getWeapon1() {
        return this.weapon1;
    }

    public void setWeapon1(String weapon1) {
        this.weapon1 = weapon1;
    }

    public String getWeapon2() {
        return this.weapon2;
    }

    public void setWeapon2(String weapon2) {
        this.weapon2 = weapon2;
    }

    public String getWeapon3() {
        return this.weapon3;
    }

    public void setWeapon3(String weapon3) {
        this.weapon3 = weapon3;
    }

    public String getAttackBonus1() {
        return this.attackBonus1;
    }

    public void setAttackBonus1(String attackBonus1) {
        this.attackBonus1 = attackBonus1;
    }

    public String getAttackBonus2() {
        return this.attackBonus2;
    }

    public void setAttackBonus2(String attackBonus2) {
        this.attackBonus2 = attackBonus2;
    }

    public String getAttackBonus3() {
        return this.attackBonus3;
    }

    public void setAttackBonus3(String attackBonus) {
        this.attackBonus3 = attackBonus;
    }

    public String getDmgType1() {
        return this.dmgType1;
    }

    public void setDmgType1(String dmgType1) {
        this.dmgType1 = dmgType1;
    }

    public String getDmgType2() {
        return this.dmgType2;
    }

    public void setDmgType2(String dmgType2) {
        this.dmgType2 = dmgType2;
    }

    public String getDmgType3() {
        return this.dmgType3;
    }

    public void setDmgType3(String dmgType3) {
        this.dmgType3 = dmgType3;
    }

    public String getAttacks() {
        return this.attacks;
    }

    public void setAttacks(String attacks) {
        this.attacks = attacks;
    }

    public String getEquipment() {
        return this.equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    public String getCopper() {
        return this.copper;
    }

    public void setCopper(String copper) {
        this.copper = copper;
    }

    public String getSilver() {
        return this.silver;
    }

    public void setSilver(String silver) {
        this.silver = silver;
    }

    public String getElectrum() {
        return this.electrum;
    }

    public void setElectrum(String electrum) {
        this.electrum = electrum;
    }

    public String getGold() {
        return this.gold;
    }

    public void setGold(String gold) {
        this.gold = gold;
    }

    public String getPlatinum() {
        return this.platinum;
    }

    public void setPlatinum(String platinum) {
        this.platinum = platinum;
    }

    public String getPassiveWisdom() {
        return this.passiveWisdom;
    }

    public void setPassiveWisdom(String passiveWisdom) {
        this.passiveWisdom = passiveWisdom;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getProficiencies() {
        return this.proficiencies;
    }

    public void setProficiencies(String proficiencies) {
        this.proficiencies = proficiencies;
    }

    public void commit() {
        Configuration cfg = new Configuration();
        cfg.configure("hibernate.cfg.xml");
        SessionFactory factory = cfg.buildSessionFactory();
        Session session = factory.openSession();
        Transaction t = session.beginTransaction();

        session.persist(this);

        t.commit();
        session.close();
    }

}
